#!/bin/sh
#
# Wrapper for the Silicon Graphics MIPSpro C and C++ compiler.  Disables
# the license 'nag' screen from stderr.
#
# Copyright 2003-2012 David Cantrell <david.l.cantrell@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

dump=1
filter_output() {
    IFS=$(echo)
    while read line ; do
        if [ ${dump} -eq 0 -o -n "$(echo $line | grep ERROR)" ]; then
            echo ${line}
        elif [ ${dump} -eq 2 ] ; then
            dump=0
        else
            tval=$(echo $line | grep "Graphics support customer then contact your local support provider.")
            [ ! -z "${tval}" ] && dump=2
        fi
    done
}

PROG="$(basename ${0})"
if [ ! -x /usr/denag/${PROG} ]; then
    echo "Missing /usr/denag/${PROG}" >&2
    exit 1
fi

/usr/denag/${PROG} "$@" 3>&2 2>&1 >&3 | filter_output
exit 0
